spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/test_db
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
    database: test_db
    host: localhost
    port: 5432
    password: root
    username: root
